ExpenseTracker/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myApp.urls')),
    path('', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
]

myApp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:id>/', views.edit_expense, name='edit_expense'),
    path('delete/<int:id>/', views.delete_expense, name='delete_expense'),
]

accounts/models.py
from django.db import models

# Create your models here.

myApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# Creating a database to store our expense
class Expense(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    name = models.CharField(max_length=100) # Field to add name of product
    amount = models.IntegerField() # Field to add the price of the product
    category = models.CharField(max_length=100) # Field to add category
    date = models.DateField(auto_now=True) # Field to save dates


    def __str__(self) -> str:
        return self.name

myApp/forms.py
from django.forms import ModelForm
from .models import Expense


class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ('name', 'amount', 'category')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login


# Create your views here.
def login(request):
    if request.method == 'POST':
        # Getting the user details from form
        username = request.POST['name']
        password = request.POST['password']
        # Authenticating the user
        user = authenticate(username=username,password=password)
        # Logging in the user
        if user is not None:
            auth_login(request, user)
            return redirect('myapp:index')
        else:
            messages.error(request, "Invalid Credentials!")
            return redirect('accounts:login')
    return render(request, 'login.html')


def register(request):
    if request.method == 'POST':
        # Getting the information about the user from our form
        username = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        # Checking if user already exist or not
        if User.objects.filter(username=username):
            messages.warning(request, "User already exists, please log in!")
            return redirect('accounts:login')
        # Saving the user to database
        myuser = User.objects.create_user(username, email, password)
        myuser.save()
        # Redirecting to login page
        return redirect('accounts:login')
    
    return render(request, 'register.html')


def logout_user(request):
    # Logging out the user
    logout(request)
    return redirect('myapp:index')

myApp/views.py
from django.shortcuts import render, redirect
from .forms import ExpenseForm
from .models import Expense
from django.db.models import Sum
import datetime as dt

# Create your views here.
def index(request):
    if request.method == 'POST':
        expense = ExpenseForm(request.POST)
        if expense.is_valid():
            # Create an instance of the expense form but don't save it yet
            expense = expense.save(commit = False) 
            # Set the user field of the expense to the currently logged-in user
            expense.user = request.user
            expense.save()
            
    expense_form = ExpenseForm()
    expenses = Expense.objects.filter(user = request.user.id)
    total_expense = expenses.aggregate(Sum('amount'))

    # Logic to calculate 365 days expenses
    last_year = dt.date.today() - dt.timedelta(days=365)
    data_year = Expense.objects.filter(date__gt = last_year, user = request.user.id)
    last_year_expense = data_year.aggregate(Sum('amount'))

    # Logic to calculate 30 days expenses
    last_month = dt.date.today() - dt.timedelta(days=30)
    data_month = Expense.objects.filter(date__gt = last_month, user = request.user.id)
    last_month_expense = data_month.aggregate(Sum('amount'))

    # Logic to calculate 30 days expenses
    last_week = dt.date.today() - dt.timedelta(days=7)
    data_week = Expense.objects.filter(date__gt = last_week, user = request.user.id)
    last_week_expense = data_week.aggregate(Sum('amount'))

    # Logic to calculate daily expense
    daily_expense = Expense.objects.filter(user = request.user.id).values('date').order_by('date').annotate(sum = Sum('amount'))
    
    # Logic to calculate expense based on category
    category_expense = Expense.objects.filter(user = request.user.id).values('category').annotate(sum = Sum('amount'))
    print(category_expense)

    context = {'expense_form': expense_form, 
               'expenses': expenses, 
               'total_expense': total_expense, 
               'last_year_expense': last_year_expense, 
               'last_month_expense': last_month_expense, 
               'last_week_expense': last_week_expense,
               'daily_expense': daily_expense,
               'category_expense': category_expense,
            }
    return render(request, 'index.html', context=context)


def edit_expense(request, id):
    expense = Expense.objects.get(id = id)
    expense_form = ExpenseForm(instance = expense)
    if request.method == 'POST':
        expense = ExpenseForm(request.POST, instance=expense)
        if expense.is_valid():
            expense.save()
            return redirect('myapp:index')
    
    return render(request, 'edit.html', {'expense_form': expense_form})


def delete_expense(request, id):
    if request.method == 'POST' and 'delete' in request.POST:
        expense = Expense.objects.get(id = id)
        expense.delete()
        return redirect('myapp:index')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Radio+Canada+Big:ital,wght@0,400..700;1,400..700&display=swap"
      rel="stylesheet"
    />

    <title>Expense Tracker</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <img src="{% static 'images/icon.png' %}" alt="" style="height: 30px;">&nbsp;
        <a class="navbar-brand" href="#">Expense Tracker</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          </ul>
        </div>
      </div>
      {% if user.is_authenticated %}
      <a class="btn btn-outline-warning my-2 my-sm-0" href="{% url 'accounts:logout' %}" style="margin-right: 30px; width:200px">
        Logout
      </a>
      {% else %}
        <a class="btn btn-outline-warning  my-2 my-sm-0" href="{% url 'accounts:login' %}" style="margin-right: 30px; width:200px">
          Login / Sign In
        </a>
      {% endif %}
    </nav>
    {% block body %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/edit.html
{% extends 'base.html' %} {% load static %} {% block body %}
<div class="container">
  <form method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Expense Name: </label>
        {{ expense_form.name }}
      </div>
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Amount: </label>
        {{ expense_form.amount }}
      </div>
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Category: </label>
        {{ expense_form.category }}
      </div>
      <div class="save-btn-container">
        <button type="submit" class="btn btn-primary save-btn">Edit</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %} {% load static %} {% load humanize %} {% block body %}
{% if request.user.is_authenticated %}
<div class="container">
  <h1 class="expense-heading">Add Expense ➕</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="row g-3">
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Expense Name: </label>
        {{ expense_form.name }}
      </div>
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Amount (in ₹): </label>
        {{ expense_form.amount }}
      </div>
      <div class="col-sm-4">
        <label for="inputEmail3" class="col-form-label">Category: </label>
        {{ expense_form.category }}
      </div>
      <div class="save-btn-container">
        <button type="submit" class="btn btn-primary save-btn">Save</button>
      </div>
    </div>
  </form>
</div>

<div class="container">
  <h1 class="expense-heading">Expenses 💲</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Expense Name</th>
        <th scope="col">Amount (in ₹)</th>
        <th scope="col">Category</th>
        <th scope="col">Date</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for expense in expenses %} {% if expense.user == request.user %}
      <tr>
        <td>{{ expense.name }}</td>
        <td>₹{{ expense.amount|intcomma }}</td>
        <td>{{ expense.category }}</td>
        <td>{{ expense.date }}</td>
        <td>
          <form
            action="{% url 'myapp:edit_expense' expense.id %}"
            method="POST"
          >
            {% csrf_token %}
            <button type="submit">
              <img
                src="{% static 'images/edit.png' %}"
                alt=""
                style="height: 15px"
              />
            </button>
          </form>
        </td>
        <td>
          <form
            action="{% url 'myapp:delete_expense' expense.id %}"
            method="POST"
          >
            {% csrf_token %}
            <button type="submit" name="delete">
              <img
                src="{% static 'images/delete.png' %}"
                alt=""
                style="height: 15px"
              />
            </button>
          </form>
        </td>
      </tr>
      {% endif %} {% endfor %}
    </tbody>
  </table>
  <br />
  <h1 class="expense-heading">
    Total Expense:<span style="color: green"
      >₹ {{ total_expense.amount__sum|intcomma }}</span
    >
  </h1>
</div>

<div
  style="
    display: flex;
    justify-content: space-between;
    padding: 50px;
    gap: 20px;
  "
>
  <div class="container">
    <h3>
      Yearly Expense:
      <span style="color: green"
        >₹ {{ last_year_expense.amount__sum|intcomma }}</span
      >
    </h3>
  </div>
  <div class="container">
    <h3>
      Monthly Expense:
      <span style="color: green"
        >₹ {{ last_month_expense.amount__sum|intcomma }}</span
      >
    </h3>
  </div>
  <div class="container">
    <h3>
      Weekly Expense:
      <span style="color: green"
        >₹ {{ last_week_expense.amount__sum|intcomma }}</span
      >
    </h3>
  </div>
</div>

<div
  style="
    display: flex;
    justify-content: space-between;
    padding: 50px;
    gap: 20px;
  "
>
  <div class="container" style="width: 450px">
    <h3 style="text-align: center">Past 30 days sum expense</h3>
    <hr />
    <table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">Dates</th>
          <th scope="col">Expense</th>
        </tr>
      </thead>
      <tbody>
        {% for daily in daily_expense %}
        <tr>
          <th scope="row">{{ daily.date }}</th>
          <td style="color: green; font-weight: bolder">₹{{ daily.sum }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container" style="width: 450px" id="cat-sum-table">
    <h3 style="text-align: center">Categorical Expense</h3>
    <hr />
    <table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">Category</th>
          <th scope="col">Expense</th>
        </tr>
      </thead>
      <tbody>
        {% for category in category_expense %}
        <tr>
          <th scope="row">{{ category.category }}</th>
          <td style="color: green; font-weight: bolder">₹{{ category.sum }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% else %}
<h1 class="expense-heading" style="text-align: center; margin-top: 10px">
  Please Login or Register
</h1>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %} {% load static %} {% block body %}
<section class="bg-light p-3 p-md-4 p-xl-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
        <div class="card border border-light-subtle rounded-4">
          <div class="card-body p-3 p-md-4 p-xl-5">
            <div class="row">
              <div class="col-12">
                <div class="mb-5">
                  <div class="text-center mb-4">
                    <a href="#!">
                      
                    </a>
                  </div>
                  <h4 class="text-center">Log In</h4>
                </div>
              </div>
            </div>
            <form action="{% url 'accounts:login' %}" method="POST">
              {% csrf_token %}
              <div class="row gy-3 overflow-hidden">
                <div class="col-12">
                  <div class="form-floating mb-3">
                    <input
                      type="text"
                      class="form-control"
                      name="name"
                      id="name"
                      placeholder="name@example.com"
                      required
                    />
                    <label for="email" class="form-label">UserName</label>
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-floating mb-3">
                    <input
                      type="password"
                      class="form-control"
                      name="password"
                      id="password"
                      value=""
                      placeholder="Password"
                      required
                    />
                    <label for="password" class="form-label">Password</label>
                  </div>
                </div>
               
                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn bsb-btn-xl btn-primary" type="submit">
                      Log In
                    </button>
                  </div>
                </div>
              </div>
            </form>
            <div class="row">
              <div class="col-12">
                <hr class="mt-5 mb-4 border-secondary-subtle" />
                <div
                  class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end"
                >
                  <a href="{% url 'accounts:register' %}" class="link-secondary text-decoration-none" style="text-align: center; margin-right:150px;"
                    >Create new account</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/register.html
{% extends 'base.html' %} {% load static %} {% block body %}
<section class="bg-light p-3 p-md-4 p-xl-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9 col-lg-7 col-xl-6 col-xxl-5">
        <div class="card border border-light-subtle rounded-4">
          <div class="card-body p-3 p-md-4 p-xl-5">
            <div class="row">
              <div class="col-12">
                <div class="mb-5">
                  <div class="text-center mb-4">
                    <a href="#!">
                      
                    </a>
                  </div>
                  <h4 class="text-center">Register</h4>
                </div>
              </div>
            </div>
            <form action="{% url 'accounts:register' %}" method="POST">
              {% csrf_token %} 
              <div class="row gy-3 overflow-hidden">
                <div class="col-12">
                  <div class="form-floating mb-3">
                    <input
                      type="email"
                      class="form-control"
                      name="email"
                      id="email"
                      placeholder="name@example.com"
                      required
                    />
                    <label for="email" class="form-label">Email</label>
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-floating mb-3">
                    <input
                      type="text"
                      class="form-control"
                      name="name"
                      id="name"
                      placeholder="name@example.com"
                      required
                    />
                    <label for="email" class="form-label">Name</label>
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-floating mb-3">
                    <input
                      type="password"
                      class="form-control"
                      name="password"
                      id="password"
                      value=""
                      placeholder="Password"
                      required
                    />
                    <label for="password" class="form-label">Password</label>
                  </div>
                </div>
               
                <div class="col-12">
                  <div class="d-grid">
                    <button class="btn bsb-btn-xl btn-primary" type="submit">
                      Register
                    </button>
                  </div>
                </div>
              </div>
            </form>
            <div class="row">
              <div class="col-12">
                <hr class="mt-5 mb-4 border-secondary-subtle" />
                <div
                  class="d-flex gap-2 gap-md-4 flex-column flex-md-row justify-content-md-end"
                >
                  <a href="{% url 'accounts:login' %}" class="link-secondary text-decoration-none" style="text-align: center; margin-right:200px;"
                    >Login</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}